FROM node:latest

RUN cd / && git clone https://github.com/aragon/aragon.git
RUN cd aragon && npm install --unsafe-perm=true --allow-root
RUN npm install -g lerna @aragon/cli truffle --unsafe-perm=true --allow-root

EXPOSE 3000

WORKDIR /aragon
CMD npm run start:local
